=== Subriti/GiftCard-Website/20049062 Subriti Aryal/catalog_20049062.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Store">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"></xs:element>
                <xs:element ref="logo"></xs:element>
                <xs:element ref="website"></xs:element>
                <xs:element ref="address"></xs:element>
                <xs:element ref="socials"></xs:element>
                <xs:element ref="telephone"></xs:element>
                <xs:element ref="Gifts"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <xs:element name="name" type="xs:string"></xs:element>

    <xs:element name="logo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="L_id" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

    <xs:attribute name="L_id" type="xs:string" />


    <xs:element name="website">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="https?://([^/:]+\.[a-zA-Z]{2,10}|([0-9]{1,3}\.){3}[0-9]{1,3})(:[0-9]+)?(/.*)?" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>


    <xs:element name="address">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="AddrType" use="optional" default="Permanent"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


    <xs:attribute name="AddrType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Permanent" />
				<xs:enumeration value="Temporary" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

    <xs:element name="socials">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
                    <xs:attribute ref="S_id" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:attribute name="S_id" type="xs:anyURI"></xs:attribute>


    <xs:element name="telephone">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ul" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <xs:element name="ul">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="li" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	
    <xs:element name="li">
        <xs:complexType>
			<xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="T_id" use="required" />
                </xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

    <xs:attribute name="T_id">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Tel_Mobile" />
				<xs:enumeration value="Tel_Work" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>


    <xs:element name="Gifts">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Gift" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <xs:element name="Gift">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="gname" minOccurs="1" maxOccurs="2" />
				<xs:element ref="type" />
				<xs:element ref="cost" />
                <xs:element ref="category"  minOccurs="0" maxOccurs="1"/>
                <xs:element ref="validity" />
				<xs:element ref="noOfUsers"  minOccurs="0" maxOccurs="1"/>
				<xs:element ref="rechargeable" />
                <xs:element ref="discount"  minOccurs="0" maxOccurs="1"/>
				<xs:element ref="payment" />
				<xs:element ref="rating"  minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute ref="id"/>
		</xs:complexType>
	</xs:element>


	<xs:element name="gname" type="xs:string"></xs:element>

    <xs:element name="type">
        <xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Physical Card" />
				<xs:enumeration value="Digital Card" />
			</xs:restriction>
		</xs:simpleType>
    </xs:element>

    
	<xs:element name="cost">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="costing" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute ref="currency" fixed="Rupees"/>
		</xs:complexType>
	</xs:element>

    <xs:attribute name="currency" type="xs:string" />

    <xs:element name="costing">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="id" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

    <xs:attribute name="id" type="xs:string" />

    <xs:element name="category" type="xs:string"/>
	
    <xs:element name="validity">
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="issue" />
                <xs:element ref="valid" />
                <xs:element ref="validRegion" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
    </xs:element>


    <xs:element name="issue">
        <xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="date" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
    </xs:element>

    <xs:attribute name="date">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="AD" />
				<xs:enumeration value="BS" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>



    <xs:element name="valid">
        <xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="period" fixed="years" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
    </xs:element>

    <xs:attribute name="period" type="xs:string" />

    <xs:element name="validRegion">
        <xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="location" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
    </xs:element>

    <xs:attribute name="location" type="xs:string" />


    <xs:element name="noOfUsers" type="xs:string"></xs:element>

    <xs:element name="rechargeable">
        <xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">    
					<xs:attribute ref="type" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
    </xs:element>

    <xs:attribute name="type" type="xs:boolean" /> 

    <xs:element name="discount" type="xs:string"></xs:element>

    <xs:element name="payment" type="xs:string"></xs:element>

    <xs:element name="rating" type="xs:string"></xs:element>
   
</xs:schema>

=== Subriti/GiftCard-Website/20049062 Subriti Aryal/catalog_20049062.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--Store is the root element here, it has details regarding itself and the giftcards which is available in its store-->
<Store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_20049062.xsd">
    <name>Gift Galore</name>
    <!--Logo stores the logo image-->
    <logo L_id="StoreLogo"></logo>
    <website>https://www.giftgalore.com</website>
    <address AddrType="Permanent">Kathmandu, Nepal</address>

    <!--Socials store the link and icons to various social profiles-->
    <socials S_id="URL"></socials>
    <telephone>
         <!-- Usage of ul list for storing of phone numbers-->
        <ul>                    
            <li T_id="Tel_Mobile">+977 9843346520</li>
            <li T_id="Tel_Work">01 5148280</li>
        </ul>
    </telephone>


    <!-- All the gift cards available in the store are written under gifts-->
    <Gifts>

        <!-- Individual gift cards are specified under Gift -->
        <Gift id="XBOX">
            <gname>XBOX</gname>
            <gname>Buy</gname>   
            <type>Physical Card</type>          <!-- The type of the gift card; digital or physical-->
            <cost currency="Rupees">            <!--Pricings of various gift cards in NPR for convenience-->
                Pricings:
                <costing id="li3">$10: Rs.1200</costing>
                <costing id="li4">$15: Rs.1800</costing>
                <costing id="li5">$25: Rs.3000</costing>
                <costing id="li6">$50: Rs.6000</costing>
            </cost>
            <validity>                          <!-- Issue, Expiry period and regions valid for the gift card-->
                <issue date="AD">Issue Date: 20/08/2021</issue>
                <valid period="years">Valid Years: 2</valid>
                <validRegion location="country">Region: Nepal</validRegion>
            </validity>
            <noOfUsers>Number Of Users: 10</noOfUsers>      <!-- Users eligible for the discount -->
            <rechargeable type="false">rechargeable: No</rechargeable>  <!-- Checks if the gift card is for one time use or money can be loaded into it -->
            <discount>Discount: 10%</discount>      <!-- The owner of the gift card gets 10% discount on services of the gift card-->
            <payment>Payment Method: Cash</payment>     <!-- Payment method for the gift card-->
            <rating>Rating: 4</rating>              <!-- Ratings/Feedbacks from the user-->
        </Gift>

        <Gift id="StarBucks">
            <gname>StarBucks</gname>
            <gname>Buy</gname>
            <type>Digital Card</type>
            <cost currency="Rupees">
                Pricings:
                <costing id="li7">$25: Rs.3000</costing>
                <costing id="li8">$50: Rs.6000</costing>
                <costing id="li9">$75: Rs.9000</costing>
            </cost>
            <category> Category: Food</category>
            <validity>
                <issue date="AD">Issue Date: 25/12/2021</issue>
                <valid period="years">Valid Years: 3</valid>
                <validRegion location="country">Region: India</validRegion>
            </validity>
            <rechargeable type="true">rechargeable: Yes</rechargeable>
            <discount>Discount: 5%</discount>
            <payment>Payment Method: Online</payment>
            <rating>Rating: 5</rating>
        </Gift>

        <Gift id="Amazon">
            <gname>Amazon</gname>
            <gname>Buy</gname>
            <type>Physical Card</type>
            <cost currency="Rupees">
                Pricings:
                <costing id="li10">$10: Rs.1200</costing>
                <costing id="li11">$25: Rs.3000</costing>
                <costing id="li12">$50: Rs.6000</costing>
                <costing id="li13">$100: Rs.12000</costing>
            </cost>
            <category> Category: E-Commerce</category>
            <validity>
                <issue date="AD">Issue Date: 25/09/2021</issue>
                <valid period="years">Valid Years: 1</valid>
                <validRegion location="country">Region: Nepal</validRegion>
            </validity>
            <noOfUsers>Number Of Users: 50</noOfUsers>
            <rechargeable type="false">rechargeable: No</rechargeable>
            <discount>Discount: 10%</discount>
            <payment>Payment Method: Cash</payment>
            <rating>Rating: 3</rating>
        </Gift>

        <Gift id="Adidas">
            <gname>Adidas</gname>
            <gname>Buy</gname>
            <type>Digital Card</type>
            <cost currency="Rupees">
                Pricings:
                <costing id="li14">$50: Rs.6000</costing>
                <costing id="li15">$100: Rs.12000</costing>
            </cost>
            <category> Category: Sports</category>
            <validity>
                <issue date="AD">Issue Date: 02/02/2021</issue>
                <valid period="years">Valid Years: 1</valid>
                <validRegion location="country">Region: Nepal</validRegion>
            </validity>
            <noOfUsers>Number Of Users: 30</noOfUsers>
            <rechargeable type="true">rechargeable: Yes</rechargeable>
            <discount>Discount: 15%</discount>
            <payment>Payment Method: Online</payment>
            <rating>Rating: 5</rating>
        </Gift>


        <Gift id="Netflix">
            <gname>Netflix</gname>
            <gname>Buy</gname>
            <type>Physical Card</type>
            <cost currency="Rupees">
                Pricings:
                <costing id="li16">$15: Rs.1800</costing>
                <costing id="li17">$30: Rs.3600</costing>
                <costing id="li18">$60: Rs.7300</costing>
            </cost>
            <category> Category: Entertainment</category>
            <validity>
                <issue date="AD">Issue Date: 10/05/2021</issue>
                <valid period="years">Valid Years: 2</valid>
                <validRegion location="country">Region: Nepal</validRegion>
            </validity>
            <noOfUsers>Number Of Users: 500</noOfUsers>
            <rechargeable type="false">rechargeable: No</rechargeable>
            <discount>Discount: 5%</discount>
            <payment>Payment Method: Cash</payment>
            <rating>Rating: 4</rating>
        </Gift>

        <Gift id="KFC">
            <gname>KFC</gname>
            <gname>Buy</gname>
            <type>Digital Card</type>
            <cost currency="Rupees">
                Pricings:
                <costing id="li19">$50: Rs.6000</costing>
                <costing id="li20">$100: Rs.12100</costing>
            </cost>
            <category> Category: Food</category>
            <validity>
                <issue date="AD">Issue Date: 18/10/2021</issue>
                <valid period="years">Valid Years: 2</valid>
                <validRegion location="country">Region: Nepal</validRegion>
            </validity>
            <noOfUsers>Number Of Users: 1000</noOfUsers>
            <rechargeable type="false">rechargeable: No</rechargeable>
            <discount>Discount: 10%</discount>
            <payment>Payment Method: Online</payment>
            <rating>Rating: 5</rating>
        </Gift>


        <Gift id="iTunes">
            <gname>iTunes</gname>
            <gname>Buy</gname>
            <type>Physical Card</type>
            <cost currency="Rupees">
                Pricings:
                <costing id="li21">$5: Rs.600</costing>
                <costing id="li22">$25: Rs.3000</costing>
                <costing id="li23">$50: Rs.6000</costing>
                <costing id="li24">$100: Rs.12100</costing>
            </cost>
            <category> Category: Entertainment</category>
            <validity>
                <issue date="AD">Issue Date: 20/02/2022</issue>
                <valid period="years">Valid Years: 3</valid>
            </validity>
            <noOfUsers>Number Of Users: 40</noOfUsers>
            <rechargeable type="true">rechargeable: Yes</rechargeable>
            <discount>Discount: 10%</discount>
            <payment>Payment Method: Cash</payment>
            <rating>Rating: 3</rating>
        </Gift>


        <Gift id="apple">
            <gname>Apple</gname>
            <gname>Buy</gname>
            <type>Digital Card</type>
            <cost currency="Rupees">
                Pricings:
                <costing id="li26">$25: Rs.3000</costing>
                <costing id="li27">$50: Rs.6000</costing>
                <costing id="li28">$100: Rs.12100</costing>
            </cost>
            <validity>
                <issue date="AD">Issue Date: 19/1/2022</issue>
                <valid period="years">Valid Years: 1</valid>
                <validRegion location="country">Region: Nepal</validRegion>
            </validity>
            <noOfUsers>Number Of Users: 500</noOfUsers>
            <rechargeable type="false">rechargeable: No</rechargeable>
            <discount>Discount: 20%</discount>
            <payment>Payment Method: Online</payment>
            <rating>Rating: 5</rating>
        </Gift>


        <Gift id="Sephora">
            <gname>Sephora</gname>
            <gname>Buy</gname>
            <type>Physical Card</type>
            <cost currency="Rupees">
                Pricings:
                <costing id="li22">$50: Rs.6000</costing>
                <costing id="li23">$100: Rs.12100</costing>
            </cost>
            <category> Category: Beauty</category>
            <validity>
                <issue date="AD">Issue Date: 12/06/2021</issue>
                <valid period="years">Valid Years: 3</valid>
                <validRegion location="country">Region: India</validRegion>
            </validity>
